name: BETA Deploy to Cloudflare Workers with Wrangler

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: build
        run: |
          yarn
          yarn build
        env:
          CI: false

      - name: deploy beta
        # You may pin to the exact commit or the version.
        uses: cloudflare/wrangler-action@2.0.0
        env:
          USER: root
        with:
          # Your Cloudflare API Token
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # The environment you'd like to publish your Workers project to - must be defined in wrangler.toml
          environment: "beta"
